
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5-v2.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5io.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5ioi.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4-v1.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4io.dtb

subdir-y	:= $(dts-dirs) overlay

